### PR TITLE
New assets for twemoji 2

### PR DESCRIPTION
**Pull request by twuttke**
According to Jason Sofonia, we are only making 72x72 pngs and svgs now. All of the latest assets are included in this patch under the /2 folder. One thing I noticed is that you have to run `utils/generate` from the `/2` subdirectory. `2/utils/generate` doesn't work.

I added some logic to generate a smaller regex by grouping all 66 diversity emoji into a common group, which reduces the minified output from 33k to 25k. The 1.0 minified code was 15k because it had far fewer flags, etc..  It is possible to generate a more elaborate regex with ranges an subgroups, that might get the code down to 20k, but it would add a lot of complexity. We do this for the server-side regex on twitter.com in Scala.

I did not add diversity or zero-width-joiner unit tests yet. It is getting late, and I wanted your feedback before doing any more work. Or we could merge this and add the unit tests as a followup.

Thank you for merging in my previous branch and refactoring things to be in a version folder. Feel free to run with this branch and make changes as necessary.

Actually, I just realized we haven't decided where the new assets will be served from.  Would it be //twemoji2.maxcdn.com/ or //twemoji.maxcdn.com/2 ?

### CODE REVIEW

**Comment by WebReflection** [comment]
where are vectorial assets? we can't provide SVG otherwise. Also assets need to go in the asset folder, not inside the versioned one.

Thanks

**Comment by twuttke** [comment]
What do you mean by vectorial assets?

I added 
/2/svg/xxx.svg (1662 items)
/2/72x72/xxx.png (1662 items)
/2/assets/xxx.ai (1662 items)

I did not overwrite add the files at the root because the legacy v1 generate script would then attempt to add diversity in the old version when it enumerates assets.

Every ai and png and svg that was already there has changed slightly, and there are about 800 new ones.

Let me know precisely where you would like me to put the new ai, svg, and png files so they dont break the old generator.

I think overwriting them on  the old location could work fine as long as we tweak the old generator to ignore the new ones. Maybe add a hard-coded whitelist to the v1 generator file?

**Comment by WebReflection** [comment]
I missed the list of `.ai` (github didn't display all files changed)  ... this means that default folder of twemoji 2 should be changed and also the svg generator should be placed inside 2/utils.

I'll merge this as it is for now and work on the rest when I can.

Thanks.

**Comment by WebReflection** [comment]
Updates:  in my case `./2/utils/generate` works without problems. After updating to the latest, can you build?

MaxCDN is kinda solved problem already, whatever lands in here, is available through the CDN.

I'll add the preview file to test all the things within the test folder.

**Comment by WebReflection** [comment]
Update: the `2/utils/generate` now works from folder root too.

The test has multiple failures: http://twitter.github.io/twemoji/2/test/

There is a preview file but it doesn't look right: http://twitter.github.io/twemoji/2/test/preview.html

Once we fix both things we can release.

I'll try to find some time to understand the preview issue but it looks like diversity is not created correctly.

Assets and default url for the CDN has also been updated.

**Comment by jakehschwartz** [comment]
@twuttke Is that Scala-ized version of the regex open source?

**Comment by twuttke** [comment]
@jakehschwartz because you want to see the common range compression, or you just want to see it in Scala?  I don't think we opened that up, but it has other extra complexity in it (like always consuming regional symbols as pairs) that probably isn't really needed now that we have so many flags.

I may take a stab at reducing the generated regex using common UCS-2 ranges, but that can sometimes backfire and destabilize things. For example, the optional skin tones modifiers are currently represented by this:
`
(?:[\\ud83c\\udffb|\\ud83c\\udffc|\\ud83c\\udffd|\\ud83c\\udffe|\\ud83c\\udfff]|)
`
But they could probably be done like this:
`
(?:\\ud83c[\\udffb-\\udfff]|)
`
The downside is, we are breaking up surrogate pairs, and some text parses may get upset with that.

If that works, though, we can collapse several other ranges. 

Scala has it easier, because they use real UTF-16, not this UCS-2 slop.

This is acceptable in Scala/Java (but not JavasScript)
`
(?:[\\ud83c\\udffb-\\ud83c\\udfff]|)
`

**Comment by jerrygrey** [comment]
@WebReflection The preview is still messed up for me on Firefox.

**Comment by WebReflection** [comment]
@jerrygrey it's a CDN, it doesn't make cache replacement that easy. I've just tried with a fresh Firefox install and I see the following which is correct.

screenshot from 2016-03-01 15-15-37

**Comment by jerrygrey** [comment]
@WebReflection No worries, thanks for this! :+1:

**Pull request merged**
