### PR TITLE
Add options.attributes callback

### PR DESCRIPTION
**Pull request by derekmooney**
Created an options.attributes feature to allow a callback (or a static object if desired) to generate custom attributes for the image tab.

I'm using this to generate aria-label and title attributes using our own descriptions / shortcut keys.

### CODE REVIEW

**Comment by jmdarts007** [comment]
Welcome friends

**Comment by WebReflection** [comment]
OK, the idea is not necessarily a bad one, but this current "execution" is:

  1. there are no tests, this is going nowehere without tests
  2. you introduced potential XSS vulnerability replacing as attribute only quotes. An object such `{'onmouseover':'alert("screwed")'}` would make it parsing text and I personally don't want to feel responsible for this.

On top of that, I beliweve attributes cannot be statics. It makes little sense, unless you want to add same attributes to every emoji. A callback, when and if the property is present, should be all you need and flexible enough to give you a way to also provide same object in case its needed.

As summary, if we can simplify the code assuming attributes is a function that returns an object and never just an object, and we can be sure that attribute name never contains `on` as prefix, and the content is correctly [escaped as HTML](https://gist.github.com/WebReflection/df05641bd04954f6d366) then yes, this PR would be welcome.

I might try to find some time to do that, but if you need this soon, feel free to update the PR.

Thank you

**Comment by derekmooney** [comment]
Thanks for the constructive and detailed feedback. I'd be happy to address any further concerns, or update documentation.

I debated on whether this mechanism should be able to override the alt attribute (currently, the DOM parsing would not allow it, and the string version would create a duplicate) or the classname (ditto). I don't need it for my purposes, but I could see case for modifying either based on the unicode value. Thoughts?

**Comment by derekmooney** [comment]
I can address these. 

Using lastIndexOf with position 0 guarantees that only one comparison will be made. Using indexOf will still search the entire string even though we don't care. I was looking around for polyfills for the proposed startsWith and was impressed with the solution (even if it's not terribly clear). I can make that a utility function if you'd prefer.

I was already wondering if it should actively filter out class, alt, draggable, and src from the attributes if they are sent out. I started updating the readme and it felt like it should be clear that not only is it not a good idea, but that it's not allowed (like the on* handlers).

If we actively filter them out, it seems like the best approach would be to just replace them into an object after the attributes call, but before the element is generated. Combining this with a default function that just returned an empty object would make the code more concise overall. This could also be factored out to be common to both DOM and string parsing.

This might make the string parsing tests a little more difficult - I assume that the ordering of the attributes is a bit stable, but I wouldn't really want the tests to rely on that as the ordering of the attributes is not *really* what needs to be tested. I wonder if the best approach for the string parsing tests in that case might be to parse the returned string and test the element and attributes via the DOM.

For the escape I was trying to go with the simplest of the solutions you outlined in your link. I rarely have to think about older browsers, I need to switch gears on that when I'm contributing.

**Comment by WebReflection** [comment]
is `lastIndexOf` compatible with IE6 ? can't remember, that's the only concern at this point (yes, it's actually clever doing that way instead of searching the entire string)

The order of attributes is totally non standard, Firefox will fail your test case indeed if used with DOM and their uterHTML representation. This is why my tests check every attributes by hand (I know, not cool, but green-light everywhere)

This code is working and tested and it targets as many browsers as possible so whatever could help specially old/non-JIT based browsers, is welcome :-)

**Comment by WebReflection** [comment]
ping

**Comment by derekmooney** [comment]
Sorry for the delay - work projects have kept me very busy. I've updated the PR, tests, and the readme based on comments, and merged back from upstream. Please let me know if we need to do anything else here, I'd like to see this wrapped up. Thanks!

**Comment by WebReflection** [comment]
OK, I might brutally fix this by myself and reject this PR. Tests are good, there are really little gotchas here and there that for consistency sake should be improved. Are you OK with this?

Otherwise, if you want:

  1. as you can see all `defaults` are static, no GC operations involved, no extra RAM needed. We should have a static fallback for attributes too ... **or** simply check if it's a function and use it only if present as attribute (but I probably prefer a default that does silently nothing)
  2. if we have a dfault such `function() {return null;}` we can use `var attrib = options.attributes(icon, variant);` and the rest would be the same. `null` should play well with JIT and V8 too when it comes to `object` or `null` ... if not, we need to think a better default.
  3. the function `escapeHTML` should could play nicer with non JIT capable browsers

```js
      // in the private var declaration list ...
      escaper = {
          '&': '&amp;',
          '<': '&lt;',
          '>': '&gt;',
          "'": '&#39;',
          '"': '&quot;'
      },
      rescaper = /[&<>'"]/g,
      ...


      // within all function declarations
      function replacer(m) {
          return escaper[m];
      }

      function escapeHTML(s) {
        return s.replace(rescaper, replacer);
      }
```

Last, but not least, the correctly escaped test with the script tag should actually contain a real `<script>` and not an already escaped one ... unless I've misunderstood the goal of that test.

**Thanks** in any case for this and plase let me know if you are too busy so I can make these changes

**Comment by WebReflection** [comment]
OK, it's probably easy like this: https://github.com/twitter/twemoji/commit/ca1c298ddd9174555d3722b4c0199c2fe010d031

That first twemoji-generator.js file is what I meant. Is that OK? If so, I can merge the whole thing from your branch, so you'll still show up as contributor. Please let me know, and thank you again!

**Comment by derekmooney** [comment]
I'm totally good with your changes - I'm more than happy to have someone fix my code up. Please feel free to merge this however you like. Thanks for your help here!

**Comment by WebReflection** [comment]
done ;-)

**Pull request merged**
