### PR TITLE
Add SELECT to the ignore list

### PR DESCRIPTION
**Pull request by pento**
The `SELECT` element and its children are not allowed to contain an `IMG` element.

### CODE REVIEW

**Comment by WebReflection** [comment]
actually not sure ... like, not at all. options can contain HTML and show emoji, if present, right? The value won't be touched being an attribute so why do you want to prevent this?

**Comment by WebReflection** [comment]
also: no tests, no merge. This is rule #1 here, I am sure you agree.

**Comment by WebReflection** [comment]
closing due no coming back

**Comment by pento** [comment]
Oops, sorry. This one slipped off my list.

Anyway, options can only contain text, no other HTML: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/option

Unfortunately, `npm install` was giving me errors, so I wasn't able to write unit tests.

Let's leave this pull request closed, as it wasn't a very good request. I'll open a new ticket, instead.

**Pull request closed without merging**
