### PR TITLE
fix skin tone regex

### PR DESCRIPTION
**Pull request by twuttke**
This is what I get for not testing... Skin tone matching should not be a character class since it needs surrogate pairs
`
(?:[\\ud83c\\udffb|\\ud83c\\udffc|\\ud83c\\udffd|\\ud83c\\udffe|\\ud83c\\udfff]|)
`
Should have been
`
(?:\\ud83c\\udffb|\\ud83c\\udffc|\\ud83c\\udffd|\\ud83c\\udffe|\\ud83c\\udfff|)
`

### CODE REVIEW

**Comment by WebReflection** [comment]
looks good with both [PNGs](http://twitter.github.io/twemoji/2/test/preview.html) and [SVGs](http://twitter.github.io/twemoji/2/test/preview-svg.html)

Thanks

**Comment by WebReflection** [comment]
so @twuttke I've updated the readme and published npm as v2

There are new build instructions and few points about breaking changes and what's new.

If you'd like to change, rephrase, or add more, feel free to PR that or just push it.

https://github.com/twitter/twemoji#twitter-emoji-twemoji-

Cheers

**Comment by twuttke** [comment]
Thanks!

I just did another PR to do keycaps better, and have one more experimental
branch to massively reduce the size of the regex using ranges. They don't
change the api at all, it is just perf/optim stuff. I guess that could be
2.1 ?

I'm not sure the ranges will work in all browsers/environments, that's why
I call it experimental. I give it 90% chance of working everywhere.



On Tue, Mar 1, 2016 at 10:32 AM, Andrea Giammarchi <notifications@github.com

**Comment by WebReflection** [comment]
ranges are handled by every browser so that's not the problem, the problem is performance with ranges that have been measured to be worst on old devices.

In any case, we still have twemoji 1 so I wouldn't care much about perf there because these could be covered by a fallback, battle tested by million devices, version of the same library.

Go ahead with ranges, actually IIRC there was already an old PR or issue regarding ranges so that maybe there is already an utility to spit out ranges from a RegExp without ranges.

@mathias is probaly the best person to tell us this.

**Comment by twuttke** [comment]
the potential problem is not just that it is a char range, it is using
ranges on half of a surrogate pair because JS doesn't do full uniode char
ranges.

i would be surprised if a char range is slower than each individual char
|ed together, but anything can happen.

anyway, i'll try it later today.  if it doesn't save much after gzip maybe
not worth doing anyway.


On Tue, Mar 1, 2016 at 12:09 PM, Andrea Giammarchi <notifications@github.com

**Comment by WebReflection** [comment]
I think it is not worth but if we have an automation that does that already that'd be great so we (you) won't waste too much time on something that worked for more than a year without a glitch in every browser ;-)

**Comment by WebReflection** [comment]
this might be the tool we are looking for: https://github.com/mathiasbynens/regenerate

**Comment by twuttke** [comment]
That's a pretty cool tool, and yes, it is pretty close to what I was
talking about.

I made a pull request with a minimal version of a char class builder
inlined. There were a few issues with the sorting because it was using the
length of the ascii escaped code points instead of the count of the UCS-2
units., and it was using parseInt(,10) on hex values, and it wasn't
recursing into all of the code points if the string was longer than 1.

I think this is worth the trouble, because the size of the library
minimized and gzipped is almost cut in half.

The current v2 has a bug in the way the minifier resolves string literals,
that is also fixed in the pull req.

- Tom

**Pull request merged**
