### PR TITLE
Don't ignore V2 files in bower.json (fixes #171)

### LINKED ISSUE #171: Why are JS files ignored in the Bower package?
Hello,

Since https://github.com/twitter/twemoji/commit/590d7a326861867964a4c1a6f1d44505fffa302b, twemoji.js is excluded from the Bower package. As I use Bower in order to easily get JS libraries, this breaks my workflow.
Is there any particular reason these files are ignored?

### PR DESCRIPTION
**Pull request by Rudloff**
Bower users probably want at least the JS files and the PNG images.

### CODE REVIEW

**Comment by WebReflection** [comment]
This is not going to work.

V2 assets are for V2 version of twemoji. The files are in the `/2` folder, anything else from the root shouldn't be there for tag v2.

Basically, I'd rather put a whitelist, if that's possible, with:

```
/2/72x72
/2/svg
/2/twemoji.amd.js
/2/twemoji.js
/2/twemoji.min.js
/2/twemoji.npm.js
```

Plus package and README + LICENSE. Is it even possible with bower logic?

**Comment by Rudloff** [comment]
I updated the PR to use a whitelist.
It produces this result:
```
bower_components/twemoji/
├── 2
│   ├── 72x72
│   ├── svg
│   ├── twemoji.amd.js
│   ├── twemoji.js
│   ├── twemoji.min.js
│   └── twemoji.npm.js
├── bower.json
├── LICENSE
├── package.json
└── README.md
```
(bower.json can't be ignored.)

**Comment by WebReflection** [comment]
should this be a minor or a patch, since it fixes a regression?

**Comment by Rudloff** [comment]
I would consider this a patch, as it only changes the metadata and not any of the code itself.

**Comment by WebReflection** [comment]
it's up. please let me know if it's OK (looks like OK to me)

**Comment by Rudloff** [comment]
I updated it in one of my projects and everything seems to be OK :)

**Pull request merged**
