### PR TITLE
Validate the first argument of parse method

### PR DESCRIPTION
**Pull request by josephj**
The first argument type of `parse` method can only be of `String` or `HTML Element`.

### CODE REVIEW

**Comment by WebReflection** [comment]
I've commented this here: https://github.com/twitter/twemoji/pull/136#issuecomment-205283021

I'd like to know what do you think. Thanks.

**Comment by josephj** [comment]
It's definitely not hard. I've already fixed that issue in our code base. Just my little feedback :)

My suggestion was majorly based on the usability of this method. As a developer, I seldom expect a 3rd-party library which deals with string or DOM would throw errors. Say if jQuery or String.js throws errors as their API design instead of the error callback or promise, they are probably not so popular now.

If the point is still not persuasive to you, I would only suggest to throw a proper error message and close my pull request and issue. Thanks.

**Comment by WebReflection** [comment]
`jQuery` has silent errors by default which is sometimes the thing developers expect, and sometimes the footgun they didn't.

Millions of sites are using this library already, including Wordpress sites, nobody until now complained about the fact parsing `undefined` should be handled somehow.

I'd like to have other developers opinion in here 'cause I know the fix is trivial, but I don't know if we want that fix in here. As example, your initial `|| ""` suggestion was assuming you only parses strings, there's no such easy fallback for DOM nodes so it takes nothing in your case to fallback to empty string, but you still need to verify the content you are trying to parse if you are passing a DOM node, otherwise everything else will break anyway ( `node.appendChild(undefined)` )

I wonder what @twuttke thinks about this.

**Comment by twuttke** [comment]
My preference is not to add bloat to a library because it increased this size of everyone's web site download. I prefer it be the responsibility of the caller to pass valid data.

In your case,  if you need garbage input to be silently ignored, then consider calling it with something like ```emoji.parse(myString || "")``` or ```myString && emoji.parse(myString)```  That way people can see at the calling level you are expecting invalid input and how you are dealing with it rather than hiding it inside the library.

Consider this:
```
"hello".concat(undefined)
```
What do you suppose that does? This is what I mean by not expecting library functions to fix invalid input, because it might not fix it the way you expect it will. In this case, it does not silently ignore the undefined. It also does not throw an exception.

As far as why not throw a detailed exception, again, I prefer not to add bloat to a library unless it adds value to most users. Is the passive "TypeError: Cannot read property 'nodeValue' of undefined(…)" exception stack enough to trace the root of the problem? If we had to choose something, maybe
```
  if (typeof what !== 'string' &&
        !(what && what.nodeName)
  ) {
    throw("Invalid arguments to Twemoji.parse");
  }
```
is a little clearer to a developer, but I'm not accustomed to that much extra run-time checking.

**Comment by WebReflection** [comment]
Agreed, I also wouldn't invalidate the cache of every `twemoji` CDN user to just add an error that is obvious to spot anyway.

I guess this is a won't fix then. Maybe we'll sneak in a better error next time there's a better reason to invalidate all caches.

**Pull request closed without merging**
