### PR TITLE
Make "Face Holding Back Tears" look better

### PR DESCRIPTION
**Pull request by jeremynoesen**
The current version of "Face Holding Back Tears" looks a little strange, and it definitely does not look like the other versions of this emoji. This artwork edit tries to make it look better by making the smile less wide, making the eyes look more towards the center, and making the eyebrows larger and lower.

### CODE REVIEW

**Comment by jeremynoesen** [comment]
Sorry for all the force pushes, I have been refining the design; however, the last five were due to git adding a file to my commit that I never added and me trying to remove it from the commit (several times).

**Comment by Zi7ar21** [comment]
Thank you, I'm not the only one that thinks it looks awkward! I suspect someone copied the SVG for another emoji, merged, them, and expected someone to clean it up before it got merged into master. By the way, I found another PR: #536

**Comment by jeremynoesen** [comment]
> Thank you, I'm not the only one that thinks it looks awkward! I suspect someone copied the SVG for another emoji, did a rough edit based on the standard's description, and expected someone to clean it up before it got merged into master (which obviously didn't happen). By the way, I found another PR: #536

I did see that other PR, however that one also felt a little messy to me. I spent a bit trying to clean this up to match the rest of the emoji set.

**Comment by Vendicated** [comment]
please do not massacre my boy 🥹 🥹 🥹 🥹

**Comment by jeremynoesen** [comment]
The new official fork of twemoji has added a more correct version of this emoji, as well as the pleading emoji. Please check it out. I will be closing this pull request, as it is no longer needed. https://github.com/jdecked/twemoji

**Pull request closed without merging**
