### PR TITLE
Compress images losslessly

### LINKED ISSUE #189: Lossless Compression
I think the images generated - png and svg files can be losslessly reduced in size drastically. 

Here's what I get from kraken.io

twemoji compression

### PR DESCRIPTION
**Pull request by technonerdz**
This PR drastically compress png and svg files. It fixes #189 !

I used https://kraken.io/web-interface to losslessly compress all of those files.

### CODE REVIEW

**Comment by WebReflection** [comment]
it sadden me you compressed old assets in 16x16 format instead of the current one :-(

**Comment by technonerdz** [comment]
What do you mean?

**Comment by technonerdz** [comment]
Where are the current one @WebReflection ? If you tell me where it is, I will do that tonight!

**Comment by WebReflection** [comment]
current `v2` related assets and code is in the folder `2`
https://github.com/twitter/twemoji/tree/gh-pages/2

**Comment by technonerdz** [comment]
it should be good!

**Comment by technonerdz** [comment]
oops I made a mistake i'll need to fix something.

**Comment by technonerdz** [comment]
I'll close this for now.. I might have to do this again.

**Comment by WebReflection** [comment]
to start with, there are no assets less than 72x72 ;-)

**Comment by technonerdz** [comment]
ok! Should I create them or not?

**Comment by WebReflection** [comment]
I don't know, I take care of the JS side of this project and I can deploy to MaxCDN.

I think designers that created those PNGs know what they did and maybe there are things like copy rights within the meta info that should remain so I hope some responsible for assets would give you an OK or explain why the PNGs are like that.

**Pull request closed without merging**
