### PR TITLE
Fix Portugal Flag 1f1f5-1f1f9

### PR DESCRIPTION
**Pull request by conorhennessy**
As @HVEVB mentioned in #414 the top right of the Portugal flag [1f1f5-1f1f9](https://raw.githubusercontent.com/twitter/twemoji/master/assets/svg/1f1f5-1f1f9.svg) is currently a bit wonky. The top right line has a gap.

I corrected this by moving the wonky yellow bar to line up with the outer circle. This part is now symmetrical with the left-hand side and corresponding part.

Here is a before & after comparison to reflect the changes made -
1f1f5-1f1f9 comparison

### CODE REVIEW

**Comment by Mennaruuk** [comment]
Hi! Do you know when this will be merged?

**Comment by conorhennessy** [comment]
Hi @Mennaruuk - nope, no idea when. 
CLA has been signed so just to wait for a Twitter Dev to merge this :)

**Comment by Mennaruuk** [comment]
> 
> 
> Hi @Mennaruuk - nope, no idea when.
> CLA has been signed so just to wait for a Twitter Dev (@jdecked maybe? 😉) to merge this small change :)

Awesomesauce. Can't wait for the new flag! Looks crispy.

**Comment by jdecked** [comment]
Good catch @conorhennessy! This will be in our next release, but I'm waiting on the Design team for the assets for the new emojis slated to be in that release too, so it'll still be another little while.

**Comment by conorhennessy** [comment]
This issue has been fixed in [v13.0.2](https://github.com/twitter/twemoji/releases/tag/v13.0.2).

**Pull request closed without merging**
