### PR TITLE
Added subdivision flags (421/1635)

### PR DESCRIPTION
**Pull request by Liggliluff**
The vector images have been created by modifying the code of already existing flag in Twemoji, either by modifiying the plain text or by the aid of Inkscape. Any element is created manually, or taken from other existing files of twemoji. If text is added, it is from any of the Google Roboto fonts, and sometimes slightly altered to better minic the original flags. No elements have been copied straight from any vector image not already in Twemoji, other than the colours. - The raster images have simply been generated from the vector images.

The vector files available on Wikipedia do have the Creative Commons Attribution-Share Alike 4.0 International license on the other hand.

The files shall have the correct file names:
1f3f4 – Black Flag (🏴)
e0030-e0039, e0061-e007a – Tag Digit Zero-Nine, Tag Latin Small Letter A-Z
e007f – Cancel Tag
https://emojipedia.org/subdivision-flags/

<table><tr><td colspan="3"><b> AE – UNITED ARAB EMIRATES</b></td></tr><tr><td>AZ – Abu Dhabi</td><td>AJ – Ajman</td><td>DU – Dubai</td></tr><tr><td>FU – Fujairah</td><td>RK – Ras al-Khaimah</td><td>SH – Sharjah</td></tr><tr><td>UQ – Umm al-Quwain</td><td></td><td></td><tr><td colspan="3"><b> BQ – CARIBBEAN NETHERLANDS</b></td></tr><tr><td>BO – Bonaire</td><td>SA – Saba</td><td>SE – Sint Eustatius</td></tr><tr><td colspan="3"><b> CL – CHILE</b></td></tr><tr><td>AN – Antofagasta</td><td>AR – Araucanía</td><td>AP – Arica y Parinacota</td></tr><tr><td>AT – Atacama</td><td>AI – Aysén</td><td>BI – Bío Bío</td></tr><tr><td>CO – Coquimbo</td><td>LI – Libertador General Bernardo O’Higgins</td><td>LL – Los Lagos</td></tr><tr><td>LR – Los Ríos</td><td>MA – Magallanes Region</td><td>ML – Maule</td></tr><tr><td>RM – Santiago Metropolitan</td><td>TA – Tarapacá</td><td>VS – Valparaíso</td></tr><tr><td colspan="3"><b> CO – COLOMBIA</b></td></tr><tr><td>AMA – Amazonas</td><td>ANT – Antioquia</td><td>ARA – Arauca</td></tr><tr><td>ATL – Atlántico</td><td>BOL – Bolívar</td><td>BOY – Boyacá</td></tr><tr><td>CAL – Caldas</td><td>DC – Capital District</td><td>CAQ – Caquetá</td></tr><tr><td>CAS – Casanare</td><td>CAU – Cauca</td><td>CES – Cesar</td></tr><tr><td>CHO – Chocó</td><td>COR – Córdoba</td><td>CUN – Cundinamarca</td></tr><tr><td>GUA – Guainía</td><td>GUV – Guaviare</td><td>HUI – Huila</td></tr><tr><td>LAG – La Guajira</td><td>MAG – Magdalena</td><td>MET – Meta</td></tr><tr><td>NAR – Nariño</td><td>NSA – Norte de Santander</td><td>PUT – Putumayo</td></tr><tr><td>QUI – Quindío</td><td>RIS – Risaralda</td><td>SAP – San Andrés & Providencia</td></tr><tr><td>SAN – Santander</td><td>SUC – Sucre</td><td>TOL – Tolima</td></tr><tr><td>VAC – Valle del Cauca</td><td>VAU – Vaupés</td><td>VID – Vichada</td></tr><tr><td colspan="3"><b> CR – COSTA RICA</b></td></tr><tr><td>A – Alajuela</td><td>C – Cartago</td><td>G – Guanacaste</td></tr><tr><td>H – Heredia</td><td>L – Limón</td><td>P – Puntarenas</td></tr><tr><td>SJ – San José</td><td></td><td></td><tr><td colspan="3"><b> DE – GERMANY</b></td></tr><tr><td>BW – Baden-Württemberg</td><td>BY – Bavaria</td><td>BE – Berlin</td></tr><tr><td>BB – Brandenburg</td><td>HB – Bremen</td><td>HH – Hamburg</td></tr><tr><td>HE – Hesse</td><td>NI – Lower Saxony</td><td>MV – Mecklenburg-Vorpommern</td></tr><tr><td>NW – North Rhine-Westphalia</td><td>RP – Rhineland-Palatinate</td><td>SL – Saarland</td></tr><tr><td>SN – Saxony</td><td>ST – Saxony-Anhalt</td><td>SH – Schleswig-Holstein</td></tr><tr><td>TH – Thuringia</td><td></td><td></td><tr><td colspan="3"><b> DK – DENMARK</b></td></tr><tr><td>84 – Capital Region</td><td>82 – Central Denmark</td><td>81 – Northern Denmark</td></tr><tr><td>83 – Southern Denmark</td><td>85 – Zealand</td><td></td><tr><td colspan="3"><b> EC – ECUADOR</b></td></tr><tr><td>A – Azuay</td><td>B – Bolívar</td><td>F – Cañar</td></tr><tr><td>C – Carchi</td><td>H – Chimborazo</td><td>X – Cotopaxi</td></tr><tr><td>O – El Oro</td><td>E – Esmeraldas</td><td>W – Galápagos</td></tr><tr><td>G – Guayas</td><td>I – Imbabura</td><td>L – Loja</td></tr><tr><td>R – Los Ríos</td><td>M – Manabí</td><td>S – Morona-Santiago</td></tr><tr><td>N – Napo</td><td>D – Orellana</td><td>Y – Pastaza</td></tr><tr><td>P – Pichincha</td><td>SE – Santa Elena</td><td>SD – Santo Domingo de los Tsáchilas</td></tr><tr><td>U – Sucumbíos</td><td>T – Tungurahua</td><td>Z – Zamora-Chinchipe</td></tr><tr><td colspan="3"><b> ES – SPAIN</b></td></tr><tr><td>AN – Andalusia</td><td>AR – Aragon</td><td>AS – Asturias</td></tr><tr><td>IB – Balearic Islands</td><td>PV – Basque Country</td><td>CN – Canary Islands</td></tr><tr><td>CB – Cantabria</td><td>CL – Castile and León</td><td>CM – Castile-La Mancha</td></tr><tr><td>CT – Catalonia</td><td>CE – Ceuta</td><td>EX – Extremadura</td></tr><tr><td>GA – Galicia</td><td>RI – La Rioja</td><td>MD – Madrid Autonomous Community</td></tr><tr><td>ML – Melilla</td><td>MC – Murcia Region</td><td>NC – Navarra Chartered Community</td></tr><tr><td>VC – Valencian Community</td><td></td><td></td><tr><td colspan="3"><b> FM – MICRONESIA, FEDERATED STATES OF</b></td></tr><tr><td>TRK – Chuuk</td><td>KSA – Kosrae</td><td>PNI – Pohnpei</td></tr><tr><td>YAP – Yap</td><td></td><td></td><tr><td colspan="3"><b> FR – FRANCE</b></td></tr><tr><td>ARA – Auvergne-Rhône-Alpes</td><td>BFC – Bourgogne-Franche-Comté</td><td>BRE – Bretagne</td></tr><tr><td>CVL – Centre-Val de Loire</td><td>CP – Clipperton Island</td><td>COR – Corse</td></tr><tr><td>GF – French Guiana</td><td>PF – French Polynesia</td><td>TF – French Southern Territories</td></tr><tr><td>GES – Grand-Est</td><td>GUA – Guadeloupe</td><td>HDF – Hauts-de-France</td></tr><tr><td>IDF – Île-de-France</td><td>LRE – La Réunion</td><td>MQ – Martinique</td></tr><tr><td>MAY – Mayotte</td><td>NC – New Caledonia</td><td>NOR – Normandie</td></tr><tr><td>NAQ – Nouvelle-Aquitaine</td><td>OCC – Occitanie</td><td>PDL – Pays-de-la-Loire</td></tr><tr><td>PAC – Provence-Alpes-Côte-d’Azur</td><td>BL – St. Barthélemy</td><td>MF – St. Martin</td></tr><tr><td>PM – St. Pierre & Miquelon</td><td>WF – Wallis & Futuna</td><td></td><tr><td colspan="3"><b> GE – GEORGIA</b></td></tr><tr><td>AB – Abkhazia</td><td>AJ – Adjara</td><td>TB – Tbilisi</td></tr><tr><td colspan="3"><b> GH – GHANA</b></td></tr><tr><td>AH – Ashanti</td><td>BA – Brong-Ahafo</td><td>CP – Central</td></tr><tr><td>EP – Eastern</td><td>AA – Greater Accra</td><td>NP – Northern</td></tr><tr><td>UE – Upper East</td><td>UW – Upper West</td><td>WP – Western</td></tr><tr><td>TV – Volta</td><td></td><td></td><tr><td colspan="3"><b> HU – HUNGARY</b></td></tr><tr><td>BK – Bács-Kiskun</td><td>BA – Baranya</td><td>BE – Békés</td></tr><tr><td>BC – Békéscsaba</td><td>BZ – Borsod-Abaúj-Zemplén</td><td>BU – Budapest</td></tr><tr><td>CS – Csongrád</td><td>DE – Debrecen</td><td>DU – Dunaújváros</td></tr><tr><td>EG – Eger</td><td>ER – Érd</td><td>FE – Fejér</td></tr><tr><td>GY – Győr</td><td>GS – Győr-Moson-Sopron</td><td>HB – Hajdú-Bihar</td></tr><tr><td>HE – Heves</td><td>HV – Hódmezővásárhely</td><td>JN – Jász-Nagykun-Szolnok</td></tr><tr><td>KV – Kaposvár</td><td>KM – Kecskemét</td><td>KE – Komárom-Esztergom</td></tr><tr><td>MI – Miskolc</td><td>NK – Nagykanizsa</td><td>NO – Nógrád</td></tr><tr><td>NY – Nyíregyháza</td><td>PS – Pécs</td><td>PE – Pest</td></tr><tr><td>ST – Salgótarján</td><td>SO – Somogy</td><td>SN – Sopron</td></tr><tr><td>SZ – Szabolcs-Szatmár-Bereg</td><td>SD – Szeged</td><td>SF – Székesfehérvár</td></tr><tr><td>SS – Szekszárd</td><td>SK – Szolnok</td><td>SH – Szombathely</td></tr><tr><td>TB – Tatabánya</td><td>TO – Tolna</td><td>VA – Vas</td></tr><tr><td>VM – Veszprém</td><td>VE – Veszprém County</td><td>ZA – Zala</td></tr><tr><td>ZE – Zalaegerszeg</td><td></td><td></td><tr><td colspan="3"><b> IE – IRELAND</b></td></tr><tr><td>C – Connacht</td><td>L – Leinster</td><td>M – Munster</td></tr><tr><td>U – Ulster</td><td></td><td></td><tr><td colspan="3"><b> KG – KYRGYZSTAN</b></td></tr><tr><td>B – Batken</td><td>GB – Bishkek</td><td>C – Chuy</td></tr><tr><td>Y – Issyk-Kul</td><td>J – Jalal-Abad</td><td>N – Naryn</td></tr><tr><td>GO – Osh</td><td>O – Osh Region</td><td>T – Talas</td></tr><tr><td colspan="3"><b> KM – COMOROS</b></td></tr><tr><td>A – Anjouan</td><td>G – Grande Comore</td><td>M – Mohéli</td></tr><tr><td colspan="3"><b> KN – SAINT KITTS AND NEVIS</b></td></tr><tr><td>N – Nevis</td><td>K – Saint Kitts</td><td></td><tr><td colspan="3"><b> LI – LIECHTENSTEIN</b></td></tr><tr><td>01 – Balzers</td><td>02 – Eschen</td><td>03 – Gamprin</td></tr><tr><td>04 – Mauren</td><td>05 – Planken</td><td>06 – Ruggell</td></tr><tr><td>07 – Schaan</td><td>08 – Schellenberg</td><td>09 – Triesen</td></tr><tr><td>10 – Triesenberg</td><td>11 – Vaduz</td><td></td><tr><td colspan="3"><b> LK – SRI LANKA</b></td></tr><tr><td>2 – Central</td><td>5 – Eastern</td><td>7 – North Central</td></tr><tr><td>6 – North Western</td><td>4 – Northern</td><td>9 – Sabaragamuwa</td></tr><tr><td>3 – Southern</td><td>8 – Uva</td><td>1 – Western</td></tr><tr><td colspan="3"><b> LR – LIBERIA</b></td></tr><tr><td>BM – Bomi</td><td>BG – Bong</td><td>GP – Gbarpolu</td></tr><tr><td>GB – Grand Bassa</td><td>CM – Grand Cape Mount</td><td>GG – Grand Gedeh</td></tr><tr><td>GK – Grand Kru</td><td>LO – Lofa</td><td>MG – Margibi</td></tr><tr><td>MY – Maryland</td><td>MO – Montserrado</td><td>NI – Nimba</td></tr><tr><td>RG – River Gee</td><td>RI – Rivercess</td><td>SI – Sinoe</td></tr><tr><td colspan="3"><b> NO – NORWAY</b></td></tr><tr><td>02 – Akershus</td><td>09 – Aust-Agder</td><td>06 – Buskerud</td></tr><tr><td>20 – Finnmark</td><td>04 – Hedmark</td><td>12 – Hordaland</td></tr><tr><td>22 – Jan Mayen</td><td>15 – Møre og Romsdal</td><td>18 – Nordland</td></tr><tr><td>17 – Nord-Trøndelag</td><td>05 – Oppland</td><td>03 – Oslo</td></tr><tr><td>11 – Rogaland</td><td>14 – Sogn og Fjordane</td><td>21 – Svalbard</td></tr><tr><td>16 – Sør-Trøndelag</td><td>08 – Telemark</td><td>19 – Troms</td></tr><tr><td>10 – Vest-Agder</td><td>07 – Vestfold</td><td>01 – Østfold</td></tr><tr><td colspan="3"><b> PK – PAKISTAN</b></td></tr><tr><td>JK – Azad Kashmir</td><td>BA – Balochistan</td><td>TA – Federally Administered Tribal Areas</td></tr><tr><td>GB – Gilgit-Baltistan</td><td>IS – Islamabad</td><td>KP – Khyber Pakhtunkhwa</td></tr><tr><td>PB – Punjab</td><td>SD – Sindh</td><td></td><tr><td colspan="3"><b> SH – SAINT HELENA</b></td></tr><tr><td>AC – Ascension Island</td><td>HL – Saint Helena</td><td>TA – Tristan da Cunha</td></tr><tr><td colspan="3"><b> SK – SLOVAKIA</b></td></tr><tr><td>BC – Banská Bystrica</td><td>BL – Bratislava</td><td>KI – Košice</td></tr><tr><td>NI – Nitra</td><td>PV – Prešov</td><td>TC – Trenčín</td></tr><tr><td>TA – Trnava</td><td>ZI – Žilina</td><td></td><tr><td colspan="3"><b> SM – SAN MARINO</b></td></tr><tr><td>01 – Acquaviva</td><td>06 – Borgo Maggiore</td><td>02 – Chiesanuova</td></tr><tr><td>03 – Domagnano</td><td>04 – Faetano</td><td>05 – Fiorentino</td></tr><tr><td>08 – Montegiardino</td><td>07 – San Marino</td><td>09 – Serravalle</td></tr><tr><td colspan="3"><b> ST – SAO TOME AND PRINCIPE</b></td></tr><tr><td>P – Príncipe</td><td>S – São Tomé</td><td></td><tr><td colspan="3"><b> SV – EL SALVADOR</b></td></tr><tr><td>AH – Ahuachapán</td><td>CA – Cabañas</td><td>CH – Chalatenango</td></tr><tr><td>CU – Cuscatlán</td><td>LI – La Libertad</td><td>PA – La Paz</td></tr><tr><td>UN – La Unión</td><td>MO – Morazán</td><td>SM – San Miguel</td></tr><tr><td>SS – San Salvador</td><td>SV – San Vicente</td><td>SA – Santa Ana</td></tr><tr><td>SO – Sonsonate</td><td>US – Usulután</td><td></td><tr><td colspan="3"><b> TL – TIMOR-LESTE</b></td></tr><tr><td>AL – Aileu</td><td>AN – Ainaro</td><td>BA – Baucau</td></tr><tr><td>BO – Bobonaro</td><td>CO – Cova Lima</td><td>DI – Dili</td></tr><tr><td>ER – Ermera</td><td>LA – Lautém</td><td>LI – Liquiçá</td></tr><tr><td>MT – Manatuto</td><td>MF – Manufahi</td><td>OE – Oecusse</td></tr><tr><td>VI – Viqueque</td><td></td><td></td><tr><td colspan="3"><b> UM – UNITED STATES MINOR OUTLYING ISLANDS</b></td></tr><tr><td>81 – Baker Island</td><td>84 – Howland Island</td><td>86 – Jarvis Island</td></tr><tr><td>67 – Johnston Atoll</td><td>89 – Kingman Reef</td><td>71 – Midway Atoll</td></tr><tr><td>76 – Navassa Island</td><td>95 – Palmyra Atoll</td><td>79 – Wake Island</td></tr><tr><td colspan="3"><b> US – UNITED STATES</b></td></tr><tr><td>AL – Alabama</td><td>AK – Alaska</td><td>AS – American Samoa</td></tr><tr><td>AZ – Arizona</td><td>AR – Arkansas</td><td>CA – California</td></tr><tr><td>CO – Colorado</td><td>CT – Connecticut</td><td>DE – Delaware</td></tr><tr><td>FL – Florida</td><td>GA – Georgia</td><td>GU – Guam</td></tr><tr><td>HI – Hawaii</td><td>ID – Idaho</td><td>IL – Illinois</td></tr><tr><td>IN – Indiana</td><td>IA – Iowa</td><td>KS – Kansas</td></tr><tr><td>KY – Kentucky</td><td>LA – Louisiana</td><td>ME – Maine</td></tr><tr><td>MD – Maryland</td><td>MA – Massachusetts</td><td>MI – Michigan</td></tr><tr><td>MN – Minnesota</td><td>MS – Mississippi</td><td>MO – Missouri</td></tr><tr><td>MT – Montana</td><td>NE – Nebraska</td><td>NH – New Hampshire</td></tr><tr><td>NJ – New Jersey</td><td>NM – New Mexico</td><td>NY – New York</td></tr><tr><td>NV – Nevada</td><td>NC – North Carolina</td><td>ND – North Dakota</td></tr><tr><td>MP – Northern Mariana Islands</td><td>OH – Ohio</td><td>OK – Oklahoma</td></tr><tr><td>OR – Oregon</td><td>PA – Pennsylvania</td><td>PR – Puerto Rico</td></tr><tr><td>RI – Rhode Island</td><td>SC – South Carolina</td><td>SD – South Dakota</td></tr><tr><td>TN – Tennessee</td><td>TX – Texas</td><td>UM – U.S. Outlying Islands</td></tr><tr><td>VI – U.S. Virgin Islands</td><td>UT – Utah</td><td>WA – Washington</td></tr><tr><td>DC – Washington DC</td><td>VT – Vermont</td><td>WV – West Virginia</td></tr><tr><td>VA – Virginia</td><td>WI – Wisconsin</td><td>WY – Wyoming</td></tr><tr><td colspan="3"><b> WF – WALLIS AND FUTUNA</b></td></tr><tr><td>AL – Alo</td><td>SG – Sigave</td><td>UV – Uvea</td></tr><tr><td colspan="3"><b> VU – VANUATU</b></td></tr><tr><td>MAP – Malampa</td><td>PAM – Penama</td><td>SAM – Sanma</td></tr><tr><td>SEE – Shefa</td><td>TAE – Tafea</td><td>TOB – Torba</td></tr>
<tr height="3"></tr>
<tr><td colspan="3"><b>Countries in progress:</b><br>
Canada (1/13), Croatia (4/21), Czechia (1/14), Egypt (1/27), Estonian (1/15), Ethiopia (6/11), Finland (2/19), Greek (1/14), Myanmar (1/15), Malaysia (3/16), Netherlands (7/18), Japan (1/47), South Africa (1/9), Switzerland (5/26), Taiwan (4/22)</td></tr>
<tr><td colspan="3"><b>Countries not started on yet:</b><br>
Croatia, Guatemala, Honduras, India, Iraq, Italy, Kenya, Latvia, Lithuania, Macedonia, Malta, Mexico, Moldova, Mongolia, Nicaragua, Palau, Papua New Guinea, Paraguay, Peru, Poland, Russia, Serbia, Solomon Islands, South Korea, South Sudan, Sweden, Ukraine, Uruguay, Venezuela</td></tr>
<tr><td colspan="3"><a href="https://github.com/Liggliluff/twemoji/pulls">Link to the pull requests of this project</a></td></tr></table>

### CODE REVIEW

**Comment by Liggliluff** [comment]
@Crissov Thank you for your criticism. I have made a few changes.

1f3f4-e0064-e0065-e0062-e0079-e007f - old 1f3f4-e0064-e0065-e0062-e0079-e007f
Both the lozenge and striped flags seems to be at the same level of being official, but the lozenge flag is an alternative flag? Anyway, I've changed it to a striped flag.

——————————

1f3f4-e0064-e0065-e0068-e0068-e007f - old 1f3f4-e0064-e0065-e0068-e0068-e007f | 1f1f0-1f1ed
The Hamburg flag has been updated to better match what the Cambodian flag looks like.

——————————

However, for the other two:
1f3f4-e0064-e0065-e0072-e0070-e007f - old 1f3f4-e0064-e0065-e0073-e006c-e007f | 1f1ea-1f1f8 1f1f7-1f1f8 1f1ea-1f1e8
Flags are made more simple, somewhat like the style of the other flags that has seals. I don't think it'll look better adding too much details to them, at least not in the Twemoji style.

**Comment by Crissov** [comment]
At *usual* emoji sizes, excessive details are unnecessary indeed. It just looked to me as if they had been stripped accidentally.

**Comment by RobinvanderVliet** [comment]
Not all ISO subdivisions do actually have flags, for example lots of Iranian subdivisions don't actually have flags. I wonder when this pull request is complete, I would like to use it in one of my projects.

**Comment by Liggliluff** [comment]
@RobinvanderVliet Your statement is correct. Not all subdivisions do have flags.
There are 3681 subdivisions total eligible for emoji flags. Out of those, I've verified that 1962 don't have flags. 4 of the codes are Great Britain which are already added. That leaves 1715 subdivisions with flags.

I'm willing to let anyone use these flags in any way they want. But I've used the source code from Twemoji, so just follow what their license agreement says.

I would also be happy if you could help adding more subdivisions too, if you are able to. There are 1210 more, which is a lot. You can push changes to my pull request, and they will be included in this pull request.

**Comment by gusbemacbe** [comment]
And Brazil, @Liggliluff ?

**Comment by Liggliluff** [comment]
@gusbemacbe Several countries are in the progress of being added, you can see all those in the pull requests to this pull request at this link: https://github.com/Liggliluff/twemoji/pulls

This is done so only fully completed countries are added to this pull request, whilst still making the flags available online for others to see the progress. Others are also allowed to add their own work to those pull requests by making a pull request to the pull requests of this pull request.

The pull request of Brazil is the following: https://github.com/Liggliluff/twemoji/pull/23 (you can go to Files changed to see the flags). Brazil has 27 flags (2 done, 25 more to do) so it will take a while to make. But the flags aren't too complicated geometrically: https://en.wikipedia.org/wiki/States_of_Brazil#List

**Comment by Liggliluff** [comment]
Split off and removed all flags from countries starting on A (Andorra, Argentina, Australia, Austria) to a separate pull request here: #345

This to create a complete pull request that is ready to be merged, instead of an incompelte one. It being only 96 files (48 flags) also makes it easier to review and handle.

This massive pull request still remains and I'm happy if people are willing to help creating more of [the missing flags](https://github.com/Liggliluff/twemoji/pulls) (this list of countries isn't complete).

**Comment by Liggliluff** [comment]
Now split off and removed all flags from countries starting on B (Bahrain, Belarus, Belgium, Bolivia, Bosnia & Herzegovina, Brazil) to a separate pull request here: #347

This massive pull request still remains and I'm happy if people are willing to help creating more of [the missing flags](https://github.com/Liggliluff/twemoji/pulls) (this list of countries isn't complete).

**Pull request closed without merging**
