### PR TITLE
Fix search order

### PR DESCRIPTION
**Pull request by twuttke**
Ugg -- don't hate me, but the secondary part of the sort function was backwards. Fixing it saves 78 bytes in the gzipped size of the library. For example, it changes this:
```
(?:\u0039|\u0038|\u0037|\u0036|\u0035|\u0034|\u0033|\u0032|\u0031|\u0030|\u0023|\u002a)
``` 
into this
(?:[\u0023\u002a\u0030-\u0039])

The reason things worked as well as they did was because for the most part, the items were already numerically sorted.

This comment is not correct:
```
    // items get sorted by length (long to short), then unicode hex values (high to low)
```

### CODE REVIEW

**Comment by WebReflection** [comment]
waiting for Travis then I'll merge

**Comment by twuttke** [comment]
Thanks. I wasn't looking too closely at that. Actually, the reason it worked well is not for the reason I said earlier. When there are two UCS-2 to compare, the second ones got swapped in the recursion.
[ 10, 1 ] would be <  [ 10, 2 ]
but
[ 10, 1 ] would be > [ 11, 1 ] 
 
Anyway, all better now. My bad.

**Comment by WebReflection** [comment]
maybe we should have some test for this to avoid future regressions?

**Comment by twuttke** [comment]
Yeah, more tests is good. Would have to break some of those out of their closures to do it, but easy enough.

Also, we don't have diversity unit tests yet other than the preview page. The iOS list is for the generic skin tones. I made that list by manually typing each Emoji on an iPad keyboard one at a time and parsing the result.

**Comment by WebReflection** [comment]
I feel like Di Caprio winning the Oscar suffered less than you doing that ... the visual feedback and the fact the HTML output does not leak anything is already a good test to me, I might rather add some extra check in the very same preview page.

Your call there, really.

**Pull request merged**
