### PR TITLE
Make size and position of face emoji more consistent

### PR DESCRIPTION
**Pull request by jasmussen**
This pull request starts work on #60. Should it be approved we'd want to export new PNGs and SVGs.

**Observations during work**

All twemoji are drawn on a 38x38 canvas in the .ai source files. All SVGs exported from these .ai files are scaled down to a 24x24px canvas. This explains the weirdly un-rounded size values such as 22,737px in the current SVGs.

Sizing and positioning issues are most noticeable with the "yellow faces". About half the "yellow face" emoji have a head-size of 36x36px inside the 38px canvas, and the other half had a smaller 34x34px head size.

**Specifics for the 1f60a to 1f62f range**

Some of those yellow face emoji are deliberately sized down, so as to make room for artwork. For example "Face With Stuck-Out Tongue And Winking Eye" has a 34x34px head size to allow for the tongue to stick out 2px below. Compare: https://cloudup.com/c0rSvWfAh5i. Since this is a deliberate creative choice, there's nothing to fix here, except push the emoji down 1px.

1f62c had a 34px head size. I compared the eye position with 1f62e and sized up the head of 1f62c. Compare: https://cloudup.com/cD6vRRdaJGJ

**Specifics for the 1f600 to 1f637 range**

There's a fair bit more variance in sizing and positioning of these yellow faces compared to the previous range. Head sizes range from 34px to 36px, and many are off centre. Compare: https://cloudup.com/ckZltnxmCy1

A lot of the smileys in this range almost hug the top of the canvas. I'm tempted to think this may have been in an effort to better align them with text, whose glyphs are traditionally shifted upwards. However since it's not consistent, and the base head size rule is broken often to make room for other creative choices, I think properly centering is probably the more desirable outcome here.

The devil horn smileys are shifted downwards and have 34px base heads, to make room for their horns. There's not much to fix here.

Some of the shades of yellow varied ever so slightly in these emoji. But this could be a creative choice, since some of the "lighter" yellow faces were angry. Such as 1f616 and 1f612.

**Summary and fixes applied**

As a summary, the set is in pretty good shape. Among the problematic yellow-face emoji, some of the nonstandard sizes were a creative choice (devil horns), in those cases I've done nothing.

The two most standard head sizes were 34px and 36px inside the 38px canvas. Specifically in the 1f600 to 1f637 range, it became clear that the 34px head size was both the most flexible (allowed more artwork like hearts and tears to go outside of the base shape), but also the most balanced in eye-to-forehead ratio.

For that reason, I've done the following to standardize:

- In cases where this size was off (such as 36px), I've standardized on the 34px head size
- In cases where emoji were off centre for no seemingly good reason, I've centered them.
- In a very few cases I had to move an eyebrow so as to keep the balanced with the slightly smaller head size, f.x. 1f62f

Where I've performed these fixes I've taken great care in ensuring that eyes, mouth and expressions didn't suddenly fall off the pixel grid, and made sure to compare with eye-sizes of similar emoji.

Here are some before/after's: https://cloudup.com/cCyeVpudNRd

### CODE REVIEW

**Comment by WebReflection** [comment]
OK, just a quick reply from me + an extra request

  1. this is **awesome**, thanks for doing it!
  2. would you please be so kind to also remove the right eye drop from 1f622 ? I don't have AI here
  3. how are we going to deal with PNGs ? I can easily export automatically to SVGs via Inkscape, but I cannot export from AI to PNG. Would you mind doing that too ?

Since I've double checked the final result, I think it's OK for me to merge and update assets.

Of course, if any designer at Twitter thinks this should not happen, we can always revert.

However, this is how it was:

screenshot from 2015-04-09 09-57-01


and this is how it is here ... and I think it's a very good job (then again, I'm not a designer)
screenshot from 2015-04-09 09-57-19

**Comment by jasmussen** [comment]
> would you please be so kind to also remove the right eye drop from 1f622 ? I don't have AI here
> how are we going to deal with PNGs ? I can easily export automatically to SVGs via Inkscape, but I cannot export from AI to PNG. Would you mind doing that too ?

Sure to both. I'll do it in a bit.

**Comment by pento** [comment]
> how are we going to deal with PNGs ? I can easily export automatically to SVGs via Inkscape, but I cannot export from AI to PNG. Would you mind doing that too ?

Inkscape can export PNGs, too.

I'm a little concerned about continuing to use Inkscape. It seems to be reading the AI files incorrectly, which is causing the SVGs to be generated at the wrong size (which is the reason `svg.sh` has to do that hackery with `sed`).

I don't know if there's an alternative option, though.

**Comment by jasmussen** [comment]
Removed the extra tear drop, and also took the liberty to reposition the sweat drop from the "cold sweat" emoji.

Upon investigating PNG exporting from Illustrator, it seems it's not as easy as I'd initially assumed. Manually doing it using save for web is possible, but the results when scaling up the vectors are slightly garbled for whatever reason. There are some batch export options I can look into, but off the cuff it's not as easy as I thought it'd be.

The ideal solution, I think, would be if we could focus on getting the .ai files right, and then having a rock solid export script that can read the .ai files and bake good PNGs and SVGs from those.

**Comment by WebReflection** [comment]
@pento Inkscape actually exports to SVG better than AI itself, which is why it got adopted in the first place: it was **not** showing up problems in any SVG compatible browser.

This, plus the fact is fully Open Source, makes Inkscape a must have. I'm also on Linux so no Win/Mac only options are a wise idea.

Please also note that exporting to PNGs with all various sizes is indeed not as straightforward as it looks. I might try to see if Inkscape does a good job there too.

**Comment by pento** [comment]
Okay, I'll keep experimenting with Inkscape. The problem is as @jasmussen mentioned earlier - Inkscape is changing the canvas size, when converting from AI to SVG, and it doesn't seem to be obeying options to set the size.

**Comment by jasmussen** [comment]
> Inkscape actually exports to SVG better than AI itself, which is why it got adopted in the first place: it was not showing up problems in any SVG compatible browser.

Illustrators SVG exporting capabilities do leave a lot to be desired. And yay open source, if we can get inkscape to work that's cool.

During my work with resizing and aligning emoji over the past couple of days I've noticed some oddities in the SVG markup itself though, which is why I raised the question of whether inkscapes exporter was solid. As an example, I compared the 1f61c emoji markup from inkscape with what Illustrator bakes. (These are the two source files: https://cloudup.com/c3io3YPEeh7)

The result from Illustrator looks like this:

```
<svg version="1.1" id="Layer_2" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 viewBox="0 0 38 38" enable-background="new 0 0 38 38" xml:space="preserve">
<path fill="#FFCC4D" d="M36,18c0,9.4-7.6,17-17,17C9.6,35,2,27.4,2,18C2,8.6,9.6,1,19,1C28.4,1,36,8.6,36,18"/>
<path fill="#664500" d="M16.5,16.8c-0.1-0.1-1.5-3.3-4.5-3.3c-3,0-4.4,3.2-4.5,3.3c-0.1,0.2,0,0.4,0.1,0.6c0.2,0.1,0.4,0.1,0.6,0
	c0,0,1.3-0.9,3.7-0.9c2.4,0,3.7,0.9,3.7,0.9c0.1,0.1,0.2,0.1,0.3,0.1c0.1,0,0.2,0,0.3-0.1C16.5,17.3,16.5,17,16.5,16.8z"/>
<circle fill="#F5F8FA" cx="25.5" cy="14.5" r="6.5"/>
<circle fill="#292F33" cx="25.5" cy="14.5" r="2.5"/>
<path fill="#664500" d="M8,23c0,4,4.6,9,11,9s11-5,11-9C30,23,19.7,25.8,8,23z"/>
<path fill="#E75A70" d="M13,24.9V31c0,3,2,6,6,6s6-3,6-6v-6C18.7,26.2,13,24.9,13,24.9z"/>
</svg>
```

Of notice is the `viewBox` which is accurately set to 38x38 matching the canvas size of the .ai source file. 

Compare that with the markup created by inkscape for the same graphic:

```
<?xml version="1.0" encoding="UTF-8" standalone="no"?><svg xmlns:svg="http://www.w3.org/2000/svg" xmlns="http://www.w3.org/2000/svg" version="1.1" viewBox="0 0 47.5 47.5" style="enable-background:new 0 0 47.5 47.5;" id="svg2" xml:space="preserve"><defs id="defs6"><clipPath id="clipPath18"><path d="M 0,38 38,38 38,0 0,0 0,38 z" id="path20"/></clipPath></defs><g transform="matrix(1.25,0,0,-1.25,0,47.5)" id="g12"><g id="g14"><g clip-path="url(#clipPath18)" id="g16"><g transform="translate(36,20)" id="g22"><path d="m 0,0 c 0,-9.389 -7.611,-17 -17,-17 -9.388,0 -17,7.611 -17,17 0,9.388 7.612,17 17,17 C -7.611,17 0,9.388 0,0" id="path24" style="fill:#ffcc4d;fill-opacity:1;fill-rule:nonzero;stroke:none"/></g><g transform="translate(16.457,21.2031)" id="g26"><path d="m 0,0 c -0.06,0.135 -1.499,3.297 -4.457,3.297 -2.957,0 -4.397,-3.162 -4.457,-3.297 -0.092,-0.207 -0.032,-0.449 0.144,-0.591 0.177,-0.143 0.427,-0.147 0.61,-0.014 0.013,0.009 1.262,0.902 3.703,0.902 2.426,0 3.674,-0.881 3.702,-0.901 0.088,-0.066 0.193,-0.099 0.298,-0.099 0.11,0 0.221,0.036 0.311,0.109 C 0.033,-0.452 0.092,-0.208 0,0" id="path28" style="fill:#664500;fill-opacity:1;fill-rule:nonzero;stroke:none"/></g><g transform="translate(32,23.5)" id="g30"><path d="m 0,0 c 0,-3.59 -2.91,-6.5 -6.5,-6.5 -3.59,0 -6.5,2.91 -6.5,6.5 0,3.59 2.91,6.5 6.5,6.5 C -2.91,6.5 0,3.59 0,0" id="path32" style="fill:#f5f8fa;fill-opacity:1;fill-rule:nonzero;stroke:none"/></g><g transform="translate(28,23.5)" id="g34"><path d="M 0,0 C 0,-1.381 -1.119,-2.5 -2.5,-2.5 -3.881,-2.5 -5,-1.381 -5,0 -5,1.381 -3.881,2.5 -2.5,2.5 -1.119,2.5 0,1.381 0,0" id="path36" style="fill:#292f33;fill-opacity:1;fill-rule:nonzero;stroke:none"/></g><g transform="translate(8,15)" id="g38"><path d="m 0,0 c 0,-3.964 4.596,-9 11,-9 6.404,0 11,5 11,9 0,0 -10.333,-2.756 -22,0" id="path40" style="fill:#664500;fill-opacity:1;fill-rule:nonzero;stroke:none"/></g><g transform="translate(13,13.1191)" id="g42"><path d="m 0,0 0,-6.083 c 0,-3 2,-6 6,-6 4,0 6,3 6,6 l 0,6.042 C 5.708,-1.333 0,0 0,0" id="path44" style="fill:#e75a70;fill-opacity:1;fill-rule:nonzero;stroke:none"/></g></g></g></g></svg>
```

The `viewBox` here is 47.5x47.5, but then there's a `clipPath` which trims that down to 38x38 again it seems. Now when I look at these two particular files side by side in a browser window, they look identical. For whatever reason, once in a while opening these SVGs in illustrator most sizes are off by just a little bit, affecting canvas size and pixel crispness. It becomes a destructive process, opening and editing an inkscape generated SVG.

**However** since it was my mistake editing SVGs instead of .AI source files in the first place, I suppose the SVG markup itself doesn't matter too much, so long as it looks the same in the browser!

**Comment by WebReflection** [comment]
FYI SVGs landed with latest push: http://twitter.github.io/twemoji/preview-svg.html

**Comment by WebReflection** [comment]
@jasmussen I can try force to 38x38 the viewBox ... I think actually that matters relatively as you can see on browsers there's no difference ;-)

**Comment by WebReflection** [comment]
never mind, that actually doesn't work and it messes up again with IE9 ... oh well, I think we are good with SVG here

**Comment by wp9015362** [comment]
> @WebReflection wrote:
> 
> would you please be so kind to also remove the right eye drop from 1f622 ?
> I don't have AI here

Thanks for forwarding this.

> @jasmussen wrote:
> 
> Removed the extra tear drop, and also took the liberty to
> reposition the sweat drop from the "cold sweat" emoji.

Thank you very much, but:

I noticed that the "face with open mouth and cold sweat" Twemoji still doesn't look correct. And I now also noticed the same for the "disappointed but relieved face" Twemoji.

See:

https://github.com/twitter/twemoji/issues/61

Can you please have a look at it?

Regards

**Pull request merged**
