### PR TITLE
fixes twitter/twemoji/issues/284

### PR DESCRIPTION
**Pull request by ArmeF97**
See #284

### CODE REVIEW

**Comment by n8downs** [comment]
Sorry, while [the spec](http://www.unicode.org/emoji/charts/emoji-list.html#1f52b) does include keywords like "revolver", the [visual consensus](https://unicode.org/emoji/charts/full-emoji-list.html#1f52b) around U+1F52B is the "water pistol" interpretation.

**Comment by Crissov** [comment]
FWIW, Emojione provides both graphics. Due to a probable veto by Apple, Unicode will probably not RGI a solution for the dilemma unless proven popular. I suggest, like the Pirate Flag, you add two custom ZWJ sequences: 🔫‍💥 for a lethal weapon and 🔫‍💦 for a toy. (The base of an emoji sequence always comes first, i.e. goes on the left, the determiner comes second after the glue, i.e. on the right, otherwise the common orientation of affected emojis would suggest the reverse order 💥🔫 and 💦🔫 or visually better 💧🔫.) Provide both in the emoji picker on the website and hide the default 🔫 without a determiner, revisit the issue in two years time.

**Comment by ArmeF97** [comment]
So, @n8downs ,
you are saying you are mantaing a implementation of the unicode standard, **_while breaking it_**?


Why should we use a non-standard font, when [emojione](https://emojipedia.org/emojione/4.5/pistol/) has stated that they will support standard?

Please reconsider this, you are creating a serious precedent. Characters can't change meanings.

**Comment by n8downs** [comment]
@ArmeF97, respectfully, I'm not sure that the standard is as cut and dry as you're making it out to be. Regarding visual representations, [the spec](https://www.unicode.org/reports/tr51/index.html#Design_Guidelines) says that "[w]hile the shape of the character can vary significantly, designers should maintain the same “core” shape, based on the shapes used mostly commonly in industry practice."

If you feel that EmojiOne's inclusion of both the lethal weapon and toy images in their set is the correct behavior, I'd encourage you to use their set over ours.

I think @Crissov's idea to create separate ZWJ sequences for the two interpretations is a good one, but I don't foresee Twemoji adding these custom sequences in the near future.

**Comment by Crissov** [comment]
To be fair, the spec was changed after the fact, because of this very issue and vendors (who make up a major of the Unicode Consortium) wanting to sanction their actions.

Custom sequences are perfectly fine and Twitter has done it before. Why do you not consider doing it again?

**Pull request closed without merging**
