### PR TITLE
Add onerror as an option

### PR DESCRIPTION
**Pull request by pento**
It'd be nice to be able to do custom error handling on occasion, this PR allows an `onerror` function to be passed to `.parse()`.

### CODE REVIEW

**Comment by pento** [comment]
See [this WordPress ticket](https://core.trac.wordpress.org/ticket/34640) for a use case.

**Comment by WebReflection** [comment]
this is not a bad idea but I don't understand the use case or the reason and there is no test with this change so it won't land as it is.

Do you mind elaborating a little bit more what is the problem  you have and what are you trying to solve? The `onerror` is something that should happen, and was thought to happen, only as network failure, not on client-side operations. Please try to let me understand what is going on, thank you

**Comment by WebReflection** [comment]
OK, I've added a test and verified that everything else is fine.  Apologies I  couldn't accept this PR witohut tests, the version `1.4.2` supports the `onerror` callback passed through options.

**Comment by pento** [comment]
Thanks, @WebReflection! I tried writing a test, but I was getting a bit stuck on the async nature of triggering the error. :-)

**Comment by WebReflection** [comment]
very dirty approach indeed but it does what it's supposed to do ;-)

https://github.com/twitter/twemoji/blob/gh-pages/test.js#L539-L555

**Pull request closed without merging**
