### PR TITLE
Added support unicode 12.0

### PR DESCRIPTION
**Pull request by crensyhanilas**
Unicode approved the emoji of unicode 12.0

https://emojipedia.org/emoji-12.0/

### CODE REVIEW

**Comment by n8downs** [comment]
This doesn't look like it makes sense as a PR?

But, we're definitely working on the new assets for Twemoji 12!

**Comment by crensyhanilas** [comment]
A merge Does not finished.

**Comment by crensyhanilas** [comment]
Wrong. need to be forked. 🍴

**Comment by crensyhanilas** [comment]
a new release for twemoji 12.0!

**Pull request closed without merging**
