### PR TITLE
Update esm.js

### PR DESCRIPTION
**Pull request by martinstuecklschwaiger**
In aea4e3238d the other files were updated but esm.js seems to have been forgotten.

### CODE REVIEW

**Comment by WebReflection** [comment]
Please sign the CLA, otherwise this looks good to me, thanks.

**Comment by martinstuecklschwaiger** [comment]
Thanks @WebReflection. Could you maybe release a new npm version, so that the change is also reflected there?

**Comment by WebReflection** [comment]
@martinstuecklschwaiger not sure I still have the rights to do so, maybe @bhaggs could help with that?

**Comment by bhaggs** [comment]
Just published the update to NPM. Should be all good now.

**Pull request merged**
