### PR TITLE
generate symbols file from svg emojis

### PR DESCRIPTION
**Pull request by barbuza**

### CODE REVIEW

**Comment by WebReflection** [comment]
What's the purpose of this PR?

**Comment by barbuza** [comment]
@WebReflection that mostly targets web performance when using twemoji icons for emoji picker (when we have to show all emojis in one page / component / etc):

1. improved download speed - 1 request for everything against 1 request for each emoji
1. reduced flickering - all emojis are displayed at the same time instead of displaying in unpredictable load order
1. each emoji is processed with SVGO so resulting symbols file should have smaller size

it's also more convenient to host just one file comparing to hosting individual emojis

**Comment by WebReflection** [comment]
there are few things that need to change in here:

  * if I understand correctly, you are targeting the root `svg` folder which is not the most updated one. You need to target `2/svg`
  * you don't improve anything with one file instead of many, when a single new emoji would mean re-downloading the entirety of the asset instead of one icon. This font-style twemoji has been discussed already, we already agreed current one file per time is the best solution, specially because users reading emoji are those consuming emoji the most and we have stats about most downloaded emoji in the CDN and it's good to have zero time and bandwidth wasted when most common emoji are already available to most surfing browsers
  * flicking shouldn't happen when you have the right CSS and your OS already supports emoji
  * AFAIK SVGs are already optimized and if SVGO removes creativecommons or other info I'm not sure we are aligned with the terms of usage
  * we're using MaxCDN as mirror/replica of this repository. If you add to `.gitignore` generated files nobody can truly enjoy the improvement you are trying to bring here, because no CDN would be used to delivery this new SVGO single file to all browsers.

If you could address these issues, this PR might be good to go for those truly needing a single file instead of many (but I'd like to know what MaxCDN folks think about this).

Thank you

**Comment by barbuza** [comment]
@WebReflection thanks for such a detailed response, I'll try to meet all the requirements you mentioned

**Comment by Crissov** [comment]
This is #90 reloaded, right?

**Comment by WebReflection** [comment]
Yes, specifically the "_if somebody pushes a PR why not_" part.

Nothing changed since then, everything said there remains **but** if there is a PR and the big sprite in some case is considered better than assets on demand, the _why not_ can be also tested and monitored.

**Comment by Crissov** [comment]
For what it's worth, Emojione and hence also Emojitwo are also automatically building an SVG file that contains all emojis.

**Pull request closed without merging**
