### PR TITLE
Add Reference To EmojiOnRoku Project

### PR DESCRIPTION
**Pull request by KasperGam**
## Description
Hi, I recently discovered this project and thought it was perfect to allow some Emoji support on Roku Scenegraph applications. This is one of my first attempts at independent open source contributions so please let me know if my project looks ok and if I attributed the work correctly. This is basically a port of this project to work on Roku applications. 

## Technical Details
I used the same base code for transforming specific code points into a URL to retrieve for each emoji. The regex provided in the https://github.com/twitter/twemoji-parser does not work for the regex functionality on Roku, since that component has the Unicode flag enabled by default (so matching based on surrogates was not working correctly). I had to instead use another emoji regex which I attributed and found here: https://github.com/mathiasbynens/emoji-regex. That project is also open source under the MIT license. 

The other work done in my project was to create a component for Roku's Scenegraph architecture that behaves roughly the same as the ordinary `Label` node, with the added bonus of recognizing and rendering emojis in much the same way as the DOM or string parser does in this project. 

## Thanks!

Thanks for the amazing project here! Again I hope this project is licensed and attributed properly, please let me know otherwise! I hope to continue to develop the project, adding multi-line support, better string truncating and adding unit tests. I think it is ready for use but could use some work as well. 

Thanks again!

### CODE REVIEW

**Comment by jdecked** [comment]
Thanks for building such a cool project!

**Comment by BROSVORN** [comment]
https://github.com/rosseljost/twemoji/commit/984204cf6b8d0cce500fab4255923d5d1af4fa1a

**Review by BROSVORN — COMMENTED** [review]
https://github.com/rosseljost/twemoji/commit/984204cf6b8d0cce500fab4255923d5d1af4fa1a

**Comment by BROSVORN** [comment]
https://github.com/twitter/twemoji

**Review by BROSVORN — COMMENTED** [review]
language: node_js
node_js:
  - "8"
git:
  depth: 1
branches:
  only:
    - gh-pages
install: yarn install --frozen-lockfile
script: yarn test

**Review by BROSVORN — COMMENTED** [review]
language: node_js
node_js:
  - "8"
git:
  depth: 1
branches:
  only:
    - gh-pages
install: yarn install --frozen-lockfile
script: yarn test

**Comment by BROSVORN** [comment]
> language: node_js
> node_js:
>   - "8"
> git:
>   depth: 1
> branches:
>   only:
>     - gh-pages
> install: yarn install --frozen-lockfile
> script: yarn test
> 

language: node_js
node_js:
  - "8"
git:
  depth: 1
branches:
  only:
    - gh-pages
install: yarn install --frozen-lockfile
script: yarn test

**Review by BROSVORN — COMMENTED** [review]
language: node_js
node_js:
  - "8"
git:
  depth: 1
branches:
  only:
    - gh-pages
install: yarn install --frozen-lockfile
script: yarn test

**Pull request merged**
