### PR TITLE
Handle keycap variants as a group in the regex

### PR DESCRIPTION
**Pull request by twuttke**
Keycap variants are not really 'non standard OSX variant' like we once thought, they are in the http://unicode.org/Public/UNIDATA/StandardizedVariants.txt file (without the trailing 20E3)

This groups all of the sensitiveKeycaps together in the regex, reducing the size of twemoji.min.js from 24881 to 24755. 

This is in preparation for my next experimental branch that collapses numerically adjacent entries into ranges, potentially cutting the size of the regex in half.

### CODE REVIEW

**Comment by twuttke** [comment]
Ok, one small wrinkle, Apple considers
U+002A U+FE0F U+20E3 
to be a valid sequence that you can enter with their Emoji keyboard even though 
002A FE0F; emoji style; # ASTERISK
DOES NOT appear in 
http://unicode.org/Public/UNIDATA/StandardizedVariants.txt
currently. 

So I will add an exception for it (not sure who to blame, Apple or the Unicode standards body)

**Comment by WebReflection** [comment]
IIRC there were already exceptions like that handled before, and it's also hard to test so please double check everything is fine through tests.

Thanks

**Comment by twuttke** [comment]
The exceptions that were there previously was a blanket exception for all keycaps (before there even was an asterisk keycap asset)  All of the other keycaps are in the variants file, so I think a specific exception for asterisk is more precise. I'll add a unit test for it.

**Comment by WebReflection** [comment]
:+1:

**Comment by twuttke** [comment]
I also added a test that validates every key you can enter on an iOS keyboard.

**Comment by twuttke** [comment]
Let me know if you think that all ios test is overkill

**Comment by WebReflection** [comment]
I think it's OK and btw, there's no `2.1` we are in version `2` so let's get it out as complete as possible (because of the way MaxCDN works, I really don't want to create hundreds folders per each sub-micro version)

**Comment by twuttke** [comment]
I have one more fix for 2639 variant

**Comment by twuttke** [comment]
ill do that in another branch since it looks like you merged this one

**Comment by WebReflection** [comment]
yeah sorry, we're using another folder and there's no official announcement yet so you can just PR to the main as long as root folder doesn't change (beside anything needed to make this version 2 happen)

**Pull request merged**
